version: '3.8'

services:
  db:
    image: postgres:14-alpine
    container_name: logingest-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: logingest
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d logingest"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: logingest-app
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=logingest
      - DB_USER=postgres
      - DB_PASSWORD=password
    volumes:
      - .:/app

volumes:
  postgres_data:
